### PR TITLE
emulation: fix for #120

### PR DESCRIPTION
**Pull request by rhornig**

### CODE REVIEW

**Comment by rhornig** [comment]
@arturscussel Check this change as it may improve the timing of the scheduler and at the same time reduce the CPU usage.

**Comment by arturscussel** [comment]
No, it's very slow, ping with 70 ms, in express mode! I had not understood the #120 , but now I think I get it, I will give a look on that.

**Comment by rhornig** [comment]
Yes, I'm testing it too. I see the slowdown too.

**Comment by arturscussel** [comment]
Yeah, the problem with that it's because now select() is blocking the code, doesn't matter if the pcap is in the immediate mode. When it is waiting the next message, it always enters on receiveWithTimeout(100000), because the targetTime is infinite (it is equal to LONG_MAX). So it's blocking it with the 100 ms timeout.

**Comment by arturscussel** [comment]
The time for processing the message it's less than 300 us, if you put receiveWithTimeout(500), in the worst case the ping will be like 800 us. And you can just alter the while header to something as while(diff_sec<1 || diff_usec<1000). The cpu usage is ok.

**Comment by rhornig** [comment]
Yeah, the fix actually is good, it's just at the same time I have increased the timeout back to 100ms because I was assuming that the select will return immediately when a packet is received. I'm not really experienced in this stuff, but why is the select blocking for 100ms if the immediate mode is set? I have assumed that that's what setting immediate does.

**Comment by arturscussel** [comment]
There was two time outs, the select's one and the pcap's one. If you see the select() parameters, you will see that it's just watching the timeout, the other thing are NULL, so it's just like a sleep. The pcap timeout doesn't exist anymore with the pcap immediate, when I call pcap_dispatch it will only check if there is a packet, if not move on.

**Comment by arturscussel** [comment]
The good side of using LINUX it's because if you look inside the #ifdef LINUX, you will see a different select(), the first parameter looks for a file descriptor associated to that pcap, so when something happens there, it leaves and you can use the receiveWithTimeout(100000), because it will leave immediately. But there is a #ifdef LINUX, so I don't know if that works for other OS, we can take it off and test is.

**Comment by arturscussel** [comment]
no, there is a function not available for windows, pcap_get_selectable_fd()

**Comment by rhornig** [comment]
I'm testing on Linux and I was wondering why the blocking happens and it turns out:
There is no such macro defined as LINUX it is called __linux__ :) which means the actual code intended for linux never ran. I have corrected this and in express mode I'm getting response times on pair with the netive interface while the CPU utilization is below 1%...

I will check check whether that function is available on Mac. If nothing else, we can have a smaller timeout on windows (and live with the higher CPU utilization) and have a longer timeout on linux.

Thanks for helping this, 
@arturscussel have a cookie @changetip

**Comment by changetip** [comment]
Hi @arturscussel, @rhornig sent you a Bitcoin tip worth a cookie (6,080 bits/$1.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/663748)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by arturscussel** [comment]
Ahhh I was wondering why it was not entering in the #ifdef, so I just put a define LINUX 1 to test if the code worked haha, quick and dirty way, thank you for the tip.

**Comment by rhornig** [comment]
Pushed a new commit. Please test it. It should now work on Linux. On other opsystems the polling tme is set to 500us which should be low enough. Please test it.

**Comment by arturscussel** [comment]
ok, here is everything working fine. Thanks

**Pull request merged**
