### PR TITLE
Fixing/New Feature #160, #162 and 163 (EtherMAC)

### PR DESCRIPTION
**Pull request by tillsteinbach**
As discussed with @ZoltanBojthe, here is the pull request.

It contains the changes for the issues: #160 , #162 and #163. If one of the changes is undesired you would have to git-cherry-pick.

**As there are changes in the statistics this might break fingerprints! So please have a careful look that I did not make a mistake!**

Best regards
Till

### CODE REVIEW

**Comment by rhornig** [comment]
As these are fixes required to be merged into the 3.x branch, could we rebase this on top of the master branch (instead of integration which will be 4.0 sometimes in the far future). Also getting rid of the upstream-merge commits would be great as they generate a lot of noise in the history.

**Comment by tillsteinbach** [comment]
Hi Rudolf,
I'll give it a try! I'm not an expert in rebasing things, thus I would suggest opening a new branch from master and cherry-picking my commits there! I'll let you know if that worked.

**Comment by rhornig** [comment]
That solution is totally acceptable and I'm doing it also in these cases :)

**Comment by tillsteinbach** [comment]
closed for new pull request #166 for master

**Pull request closed without merging**
