### PR TITLE
sctp: SCTPSocket improvements and clean-ups

### PR DESCRIPTION
**Pull request by dreibh**
sctp: Clean-ups and fixes for the SCTPSocket class:
- Removed unused attribute "sockId"
- Improved debug output
- Merged 3 ugly send() call variants into a single one + call for cmsg-type control messages.
- Simplified connectx(): call to connect() with first address (the same behaviour as before, but without code duplication).
- Added socketDeleted() method to callback API.
- Changed SCTPSocket's socketStatusArrived() behaviour to be the same as for TCP: "status" needs to be deleted within socketStatusArrived().
- cPacket/cMessage usage fixes.

### CODE REVIEW

**Comment by rhornig** [comment]
Hi @dreibh, I've tried to test this pull request and realized that the fingerprint tests now fail for SCTP related tests. A bit more investigation shows that the tests broke on an earlier pull request 02ca987d61d74e928aac3b9cfd1a789aedb315c9 . It seems that the packet->msg change was not fully carried out. Could you please take care of it and make sure that the tests/fingerprint/fingerprints script passes?

**Comment by dreibh** [comment]
Hi @rhornig, I have added some updates and further fixes, i.e. the fingerprints are working now.

**Comment by rhornig** [comment]
Thanks I will test out soon.

**Comment by rhornig** [comment]
@dreibh 

I've just tested this branch and it seems that the following examples are still failing after the change:
  /examples/ipv6/nclients/ -f omnetpp.ini -c PPP_SCTP -r 0 (some fingerprint mismatch; actual  '0cef-c286')
  /examples/sctp/cmttest/ -f omnetpp.ini -c General -r 0 (some fingerprint mismatch; actual  'b8db-b320')
  /examples/sctp/multihomed/ -f omnetpp.ini -c General -r 0 (some fingerprint mismatch; actual  '50b7-1aaa')
  /examples/sctp/nclients/ -f omnetpp.ini -c General -r 0 (some fingerprint mismatch; actual  'a206-092a')

Could you look into the issue? If the changes are justified, just update the fingerprints.

**Comment by rhornig** [comment]
I have merged these changes as 8c52330748d448873c3b571fc3d0990944ace4dc but please amend this pullrequest to fix the fingerprint or the code (depending which one is correct :)

**Pull request closed without merging**
