### PR TITLE
Prevent dereferencing dangling Radio pointer in RadioMedium

### PR DESCRIPTION
**Pull request by riebl**
This pull request relates to #250.
I have discarded the previous idea to replace IRadio pointers by radio ids for two reasons:
1) Ids from IRadio::getId() cannot be turned into cModule easily because it is not inherited from cModule::getId(). A workaround would require look-ups at RadioMedium.
2) I am not sure if it is possible to create any reasonable return value in DimensionalAnalogModelBase::computeReceptionPower at all when there is no transmitter radio available any more.

Hence, I have picked up and modified the initial idea by Nico Brüttner. For faster lookups, std::set is used instead of std::vector to store IRadio* in RadioMedium. Fingerprints remain unchanged and wireless tests are still running fine.

### CODE REVIEW

**Comment by levy** [comment]
I thought that we are going to change the reception process in a way that allows receiving signals despite the transmitter has been already removed from the medium while the signal was propagating. This change simply ignores a signal at the receiver if the transmitter has been already removed removed from the medium, which is clearly just a kludge. I understand that this change avoids the crash, but you could also avoid that by carefully removing a radio after it stopped transmitting for a certain amount of time. I also understand your (2) point, namely that it's not trivial to change the reception process in a way that completely avoids querying the transmitter radio. We would have to copy all relevant information to the signal during the transmission. I'm reluctant to include this change in it's current form due to the above reasoning.

**Comment by riebl** [comment]
I am very well aware that this pull request is only a crude workaround. Are you willing to accept a patch which includes severer changes at ITransmission? From my point of view, only antenna properties are really missing in ITransmission right now: ITransmission::getTransmitter()::getAntenna() is a prerequisite for calculating antenna gains.
Extending the lifetime of IAntenna (and consequently IMobility) compared to the related IRadio seems to be unfavourable to me considering that AntennaBase is a cModule (for good reason) and thus can hardly be managed by a kind of smart pointer. Not even speaking about the IMobility trouble arising then…
Honestly, I am not sure how to solve this issue in a nice way. Maybe a std::shared_ptr<IAntennaProperties> returned by IAntenna::getProperties()? This shared_ptr could be included in ITransmission and be used for gain computations instead.

**Comment by levy** [comment]
Hmm, this issue seems to be much deeper than we anticipated. The transmitter cannot foresee all potential receivers, especially those which may not yet be known by the medium, at the time of the transmission. So if we allow the transmitter to be deleted while the signal propagates, then we have to make sure that the transmitter antenna data is available by some other means at the receiver during the reception. This is required to compute directional selectivity for the transmitter antenna.

In general, any physical property of the transmitter that may affect the reception of a signal, and which may be altered over time (either by the destruction of the transmitter or simply by changing it on the transmitter) must be copied to the transmission. This includes position, orientation, modulation, encoding, power, frequency, etc. **and antenna data**. I think shared_ptr would only solve the destruction case but not the modification case. Besides, there's no shared_ptr right now in INET.

I think right now it seems to be easier for your case to delay the removing of the radio. You could delay the removing until a safe moment, when all of the radio's transmissions have been already removed from the medium.

As for the long run, I think this issue should be solved by copying all relevant data to the transmission so it stands on its own feet.

**Comment by riebl** [comment]
I was thinking of std::shared_ptr (INET makes already use of C++11, so this one is available) to reduce the overhead caused by each Transmission creation. Most of the time the antenna properties are quite static. Maybe a custom smart pointer with copy-on-write semantics could help us here? Such a smart pointer would also behave correctly for the modification case you have mentioned.

**Comment by levy** [comment]
Should I close this one too after the merge of #266, or is there any value left in it?

**Comment by riebl** [comment]
I close this pull request because it is completely superseded by #266. Thank you for all the good comments!

**Pull request closed without merging**
