### PR TITLE
TCP: fix bug #803 "TCP SACK issue". Author: Thomas Reschka

### PR DESCRIPTION
**Pull request by avarga**
Please review this commit.

### CODE REVIEW

**Comment by avarga** [comment]
Under review by @scimbe

**Comment by scimbe** [comment]
In process...

**Comment by rhornig** [comment]
@scimbe Any news on this? If its ok, I would love to merge it.

**Comment by scimbe** [comment]
Unfortunately I had no environment around to test it well. 
It will need minimum two more weeks, because I will get new hardware and software 
and I have to setup simulation pool to get an overview about the issue. 
Perhaps it is an alternative to merge this and to open a ticket assigned to me in the bug tracking tool... But that is up to you... 
This patch provides an improvement...

**Comment by scimbe** [comment]
An additional push request?

Rudolf Hornig <notifications@github.com> schrieb am Mo., 23. Feb. 2015
17:40:

**Comment by rhornig** [comment]
@scimbe  No, need to do anything special except please review the code change (single line) and whether i *correctly* solves the problem described in: http://dev.omnetpp.org/bugs/view.php?id=803

If you need more time, it's not a problem. We do not have the domain knowledge to decide whether this solution is ok or not. If you approve it, I will merge immediately.

**Pull request closed without merging**
