### PR TITLE
extLowerInterface emulation fix

### LINKED ISSUE #847: A bug occurs when the TsnSwitch uses the ExtLowerEthernetInterface
I hope to transmit the real stream to the TSN network, such as UDP packets, to realize the TSN emulation. However, I encountered a BUG when configuring the ExtLowerEthernetInterface for the TsnSwitch.

```
Gate 'phys$i' of compound module (inet::ExtInterface)DumbbellNetwork.switch1.eth[0] is not connected on the inside, upon arrival of message (inet::physicallayer::Signal)best effort-0 -- in module (inet::PacketTransmitter) DumbbellNetwork.client1.eth[0].phyLayer.transmitter (id=133), at t=0s, event #14
```

I don't know how to configure to solve this problem.

Here is my network topology. I use 3 virtual machines, two of which act as the real sender and receiver, and the remaining one runs omnetpp.

Hers is my ned file.

```ned
//
// SPDX-License-Identifier: LGPL-3.0-or-later
//


package inet.showcases.tsn.My_workspace.nedfile;

import inet.networks.base.TsnNetworkBase;
import inet.node.contract.IEthernetNetworkNode;
import inet.node.ethernet.EthernetLink;

network DumbbellNetwork extends TsnNetworkBase
{
    parameters:
        *.eth[*].bitrate = default(100Mbps);
    submodules:
        client1: <default("TsnDevice")> like IEthernetNetworkNode {
            @display("p=300,150");
            gates:
                ethg[1];
        }
        switch1: <default("TsnSwitch")> like IEthernetNetworkNode {
            @display("p=500,250");
            gates:
                ethg[2];
        }
        switch2: <default("TsnSwitch")> like IEthernetNetworkNode {
            @display("p=700,250");
            gates:
                ethg[2];
        }
        server1: <default("TsnDevice")> like IEthernetNetworkNode {
            @display("p=900,150");
            gates:
                ethg[1];
        }
    connections:
        client1.ethg[0] <--> EthernetLink <--> switch1.ethg[0];
        switch2.ethg[1] <--> EthernetLink <--> server1.ethg[0];
        switch1.ethg[1] <--> EthernetLink <--> switch2.ethg[0];
}
```

Here is my ini file.

```ini
[General]
scheduler-class = "inet::RealTimeScheduler"
network = inet.showcases.tsn.My_workspace.nedfile.DumbbellNetwork
description = "TSN HIL"
**.fcsMode = "computed"  
**.crcMode = "computed"
sim-time-limit = 600s


**.displayGateSchedules = true
**.gateFilter = "**.eth[1].**"
**.gateScheduleVisualizer.height = 16
**.gateScheduleVisualizer.placementHint = "top"


*.client1.numApps = 2
*.client1.app[*].typename = "UdpSourceApp"
*.client1.app[0].display-name = "best effort"
*.client1.app[1].display-name = "video"
*.client1.app[*].io.destAddress = "server1"
*.client1.app[0].io.destPort = 1000
*.client1.app[1].io.destPort = 1001
*.client1.app[*].source.packetLength = 1000B - 54B # 42B = 8B (UDP) + 20B (IP) + 14B (ETH MAC) + 4B (ETH FCS) + 8B (ETH PHY)
*.client1.app[0].source.productionInterval = exponential(200us) # ~40Mbps
*.client1.app[1].source.productionInterval = exponential(400us) # ~20Mbps

*.client1.hasOutgoingStreams = true

*.client1.bridging.streamIdentifier.identifier.mapping = [{stream: "best effort", packetFilter: expr(udp.destPort == 1000)},
                                                         {stream: "video", packetFilter: expr(udp.destPort == 1001)}]
*.client1.bridging.streamCoder.encoder.mapping = [{stream: "best effort", pcp: 0},
                                                 {stream: "video", pcp: 4}]


*.server1.numApps = 2
*.server1.app[*].typename = "UdpSinkApp"
*.server1.app[0].io.localPort = 1000
*.server1.app[1].io.localPort = 1001
*.server1.hasIncomingStreams = true


**.numPcapRecorders = 1
**.client1.pcapRecorder[0].pcapFile = "results/client1.pcap"
**.server1.pcapRecorder[0].pcapFile = "results/server1.pcap"
**.switch1.pcapRecorder[0].pcapFile = "results/switch1.pcap"
**.switch2.pcapRecorder[0].pcapFile = "results/switch2.pcap"

**.forwarding = false



*.switch1.typename = "TsnSwitch1"
*.switch2.typename = "TsnSwitch2"
*.switch*.hasIncomingStreams = true
*.switch*.hasOutgoingStreams = true
*.switch*.bridging.streamCoder.decoder.mapping = [{pcp: 0, stream: "best effort"},
                                                  {pcp: 4, stream: "video"}]

*.switch*.bridging.streamCoder.encoder.mapping = [{stream: "best effort", pcp: 0},
                                                  {stream: "video", pcp: 4}]

*.switch1.numEthInterfaces =1
*.switch2.numEthInterfaces =1
*.switch1.eth[0].typename = "ExtLowerEthernetInterface"  
*.switch1.eth[0].mtu = 1500B  
*.switch1.eth[0].device = "ens36" 
*.switch1.eth[0].address="00-0c-29-4e-75-07"
*.switch2.eth[0].typename = "ExtLowerEthernetInterface"  
*.switch2.eth[0].mtu = 1500B  
*.switch2.eth[0].device = "ens38" 
*.switch2.eth[0].address="00-0c-29-4e-75-11"


*.switch1.hasEgressTrafficShaping = true
*.switch2.hasEgressTrafficShaping = true
*.switch1.eth[1].macLayer.queue.numTrafficClasses = 2
*.switch1.eth[2].macLayer.queue.numTrafficClasses = 2
*.switch2.eth[1].macLayer.queue.numTrafficClasses = 2
*.switch2.eth[2].macLayer.queue.numTrafficClasses = 2
*.switch1.eth[1].macLayer.queue.*[0].display-name = "best effort"
*.switch1.eth[2].macLayer.queue.*[0].display-name = "best effort"
*.switch2.eth[1].macLayer.queue.*[0].display-name = "best effort"
*.switch2.eth[2].macLayer.queue.*[0].display-name = "best effort"
*.switch1.eth[1].macLayer.queue.*[1].display-name = "video"
*.switch1.eth[2].macLayer.queue.*[1].display-name = "video"
*.switch2.eth[1].macLayer.queue.*[1].display-name = "video"
*.switch2.eth[2].macLayer.queue.*[1].display-name = "video"
*.switch1.eth[1].macLayer.queue.transmissionGate[0].offset = 0ms
*.switch1.eth[2].macLayer.queue.transmissionGate[0].offset = 0ms
*.switch1.eth[1].macLayer.queue.transmissionGate[0].durations = [4ms, 6ms] # period is 10 # length of periods
*.switch1.eth[2].macLayer.queue.transmissionGate[0].durations = [4ms, 6ms] # period is 10 # length of periods
*.switch1.eth[1].macLayer.queue.transmissionGate[1].offset = 6ms
*.switch1.eth[2].macLayer.queue.transmissionGate[1].offset = 6ms
*.switch1.eth[1].macLayer.queue.transmissionGate[1].durations = [2ms, 8ms]
*.switch1.eth[2].macLayer.queue.transmissionGate[1].durations = [2ms, 8ms
*.switch2.eth[1].macLayer.queue.transmissionGate[0].offset = 10ms
*.switch2.eth[2].macLayer.queue.transmissionGate[0].offset = 10ms
*.switch2.eth[1].macLayer.queue.transmissionGate[0].durations = [4ms, 6ms] # period is 10 # length of periods
*.switch2.eth[2].macLayer.queue.transmissionGate[0].durations = [4ms, 6ms] # period is 10 # length of periods
*.switch2.eth[1].macLayer.queue.transmissionGate[1].offset = 16ms
*.switch2.eth[2].macLayer.queue.transmissionGate[1].offset = 16ms
*.switch2.eth[1].macLayer.queue.transmissionGate[1].durations = [2ms, 8ms]
*.switch2.eth[2].macLayer.queue.transmissionGate[1].durations = [2ms, 8ms]
```

I know it's probably some silly mistake, but do you have idea about how to use ExtLowerEthernetInterface in TsnSwitch?    

Thanks!

### PR DESCRIPTION
**Pull request by DBC201**
close #847

### CODE REVIEW

**Comment by levy** [comment]
I don't know what you are trying to achieve with this PR. The purpose of ExtLowerEthernetInterface is to send packets to the host OS device. It cannot be used with TSN priority queueing at the moment.

**Comment by DBC201** [comment]
Hello @levy, it doesn't allow any packets to be sent to the host os at all, no matter which node you use it with. I tried a regular switch, standardhost, ethernethost... It also gives the same error on all when it receives packets in the simulation, when used in this manner from omnetpp.ini without modifying the ned files. This is because the inout phys gate in extLowerEthernetInterface.ned is declared but it's not connected to anything in the file. I have fixed the writing issue by connecting this. 

Also, I changed the part it writes to the nic, since it tries to write the whole simulation packet, not excluding the data added by the physical layer.

Please correct me if my assumptions are wrong. In my opinion, I believe extLowerEthernetInterface should be it's own node instead of being initialized like this in omnetpp.ini. Because it is connecting to the nic device of the host computer, it is effectively connecting to an external real network, i.e. the cloud. I would actually be happy to open a pull request that implements this, I have also done some work on this as well. Thank you for your time.

**Comment by levy** [comment]
There are examples which use the ExtLowerEthernetInterface module, so it should work as intended. For example, in the examples/emulation/pinger folder you will find a working example, but there are others.

```
levy@valardohaeris:~/workspace/inet/examples/emulation/pinger$ ./run.sh 
OMNeT++ Discrete Event Simulation  (C) 1992-2022 Andras Varga, OpenSim Ltd.
Version: 6.1pre1, build: internal, edition: Academic Public License -- NOT FOR COMMERCIAL USE
See the license for distribution terms and warranty disclaimer

Setting up Cmdenv...

Loading NED files from /home/levy/workspace/inet/examples:  189
Loading NED files from /home/levy/workspace/inet/showcases:  77
Loading NED files from /home/levy/workspace/inet/src:  1200
Loading NED files from /home/levy/workspace/inet/tests/validation:  5
Loading NED files from /home/levy/workspace/inet/tests/networks:  6
Loading NED files from /home/levy/workspace/inet/tutorials:  20

Preparing for running configuration General, run #0...
Assigned runID=General-0-20240327-15:19:34-122062
Setting up network "ExtPingerExample"...
Initializing...

Running simulation...
** Event #0   t=0   Elapsed: 1.9e-05s (0m 00s)  0% completed  (0% total)
     Speed:     ev/sec=0   simsec/sec=0   ev/simsec=0
     Messages:  created: 17   present: 17   in FES: 2
ExtPingerExample.peer.app[0]: reply of 56 bytes from 192.168.2.2 icmp_seq=0 ttl=64 time=3.543303696 msec (Ext-ICMPv4-ECHO-REPLY-4)
ExtPingerExample.peer.app[0]: reply of 56 bytes from 192.168.2.2 icmp_seq=1 ttl=64 time=1.132277696 msec (Ext-ICMPv4-ECHO-REPLY-29)
ExtPingerExample.peer.app[0]: reply of 56 bytes from 192.168.2.2 icmp_seq=2 ttl=64 time=1.378474696 msec (Ext-ICMPv4-ECHO-REPLY-36)
ExtPingerExample.peer.app[0]: reply of 56 bytes from 192.168.2.2 icmp_seq=3 ttl=64 time=1.417817696 msec (Ext-ICMPv4-ECHO-REPLY-42)
^C** Event #97   t=4.548813502304   Elapsed: 4.49919s (0m 04s)  45% completed  (45% total)
     Speed:     ev/sec=21.5595   simsec/sec=1.01103   ev/simsec=21.3242
     Messages:  created: 75   present: 18   in FES: 3

<!> SIGINT or SIGTERM received, exiting -- at t=4.548813502304s, event #97

Calling finish() at end of Run #0...
5 packets sent, 46 packets received
[INFO]	ExtPingerExample.peer.tcp: finishing with 0 connections open.
--------------------------------------------------------
	ExtPingerExample.peer.app[0]
--------------------------------------------------------
sent: 5   received: 4   loss rate (%): 20
round-trip min/avg/max (ms): 1.13228/1.86797/3.5433
stddev (ms): 1.12401   variance:1.26341e-06
--------------------------------------------------------
[DEBUG]	Ipv4::flush(): pending packets:
[DEBUG]	Ipv4::flush(): packets in hooks: 0
[INFO]	Clear all sockets

End.
```

The ExtLowerEthernetInterface module is a network interface and not a network node. The phys gate is defined to be loose that means it can be unconnected internally and it doesn't have to be connected externally either.

**Comment by DBC201** [comment]
In the pinger example the frame never leaves the node. This issue occurs when a frame is sent from another node to the gate which ExtLowerEthernetInterface is set up. If I understand correctly, the electric signal is not decapsulated correctly to ethernet mac.

```
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
// 

package test_simulation;

import inet.networklayer.configurator.ipv4.Ipv4NetworkConfigurator;
import inet.node.ethernet.Eth100M;
import inet.node.ethernet.EthernetHost;
import inet.node.ethernet.EthernetSwitch;
import inet.node.inet.Router;
import inet.node.inet.StandardHost;


network extlowerethinterface_test
{
    @display("bgb=729,462");
    submodules:
        configurator: Ipv4NetworkConfigurator {
            @display("p=104,144");
        }
        standardHost: StandardHost {
            @display("p=331,144");
        }
        ethernetHost: EthernetHost {
            @display("p=544,366");
        }
    connections:
        ethernetHost.ethg <--> Eth100M <--> standardHost.ethg++;
}
```

```
scheduler-class = "inet::RealTimeScheduler"
network = extlowerethinterface_test

*.standardHost.eth[0].typename = "ExtLowerEthernetInterface"
*.standardHost.eth[0].device = "enp46s0"
*.standardHost.eth[0].copyConfiguration = "copyFromExt"

*.ethernetHost.cli.destAddress = "standardHost"
*.ethernetHost.cli.sendInterval = 1s
*.ethernetHost.cli.respLength = 1Kib
*.crcMode = "computed"
**.fcsMode = "computed"
**.duplexMode = true
**.eth*.bitrate = 100Mbps
```

image

**Comment by DBC201** [comment]
Oh I see, the gate interacting with the host os is supposed to be internal within the node. It worked when I set it up this way as you stated. However, #847 makes the same mistake I did, if you look at his .ned file. The error is related to that, tsn might not be implemented but his current error is the same as mine.

So this worked for me, if anyone else is reading this pr for a solution:
```
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with this program.  If not, see http://www.gnu.org/licenses/.
// 

package test_simulation;

import inet.networklayer.configurator.ipv4.Ipv4NetworkConfigurator;
import inet.node.ethernet.Eth100M;
import inet.node.ethernet.EthernetHost;
import inet.node.ethernet.EthernetSwitch;
import inet.node.inet.Router;
import inet.node.inet.StandardHost;


network extlowerethinterface_test
{
    @display("bgb=729,462");
    submodules:
        configurator: Ipv4NetworkConfigurator {
            @display("p=104,144");
        }
        ethernetSwitch: EthernetSwitch {
            @display("p=210,249");
            gates:
                ethg[2];
        }
        ethernetSwitch1: EthernetSwitch {
            @display("p=473,282");
            gates:
                ethg[2];
        }
    connections allowunconnected:
        ethernetSwitch.ethg[1] <--> Eth100M <--> ethernetSwitch1.ethg[1];
}```

```
scheduler-class = "inet::RealTimeScheduler"
network = extlowerethinterface_test


*.ethernetSwitch.eth[0].typename = "ExtLowerEthernetInterface"
*.ethernetSwitch.eth[0].device = "enp46s0"
*.ethernetSwitch.eth[0].copyConfiguration = "copyFromExt"

*.ethernetSwitch1.eth[0].typename = "ExtLowerEthernetInterface"
*.ethernetSwitch1.eth[0].device = "lo"
*.ethernetSwitch1.eth[0].copyConfiguration = "copyFromExt"

**.crcMode = "computed"
**.fcsMode = "computed"
**.duplexMode = true
**.eth*.bitrate = 100Mbps
```

**Comment by levy** [comment]
Yes, I have already commented on #847

**Comment by DBC201** [comment]
Oh, I just saw that. Thank you for your help and patience. I couldn't distinguish well how extLowerInterface was supposed to be used and not connected externally. I didn't realize there was an examples folder when I first started learning about inet and either it wasn't obvious or I missed it on the web ui documentation. The showcases were using apps, so I was having this issue and found this github issue instead. It has been a few months since I have been using inet and I am still very much new. Thanks again.

**Pull request closed without merging**
