### PR TITLE
Topic/redmarker final

### PR DESCRIPTION
**Pull request by screw**
Submitting RedMarker - module based on RedDropper (RED-Random Early Detection).

It supports only Eth2 -> Ipv4 encapsulation.
Marks only IPv4 packets with DiffServ two least significant bits - ECN bits - (Explicit Congestion Notification) - capability (IP_ECN_ECT_0 or IP_ECN_ECT_1;   ECT-> ECN Capable Transport).

It marks packet if avg queue lenght > maxth or random  when  minth < avg < maxth.
It drops packet when the current queue legth is bigger than max allowed size.

Traffic that is not supported (non-Eth2, Ipv6, Ipv4 without ECT) is handled by RedDropper - but packets are dropped only when exceeding max size.

1. I want to push it to INET upstream in case somebody else finds it useful.
2. It is the first step for integrating DataCenter TCP which uses ECN marks.
3. I want to get feedback on how to update packet mid-way (in-network) and correctly handle front and back offset with the (still new for me) INETv4 packet representation.

The resulting compound module RedMarkerQueue is used as follows:

**.router.eth[*].queue.typename       = "RedMarkerQueue"
**.router.eth[*].queue.red.wq         = 1 
**.router.eth[*].queue.red.minths     = "3" #"5"
**.router.eth[*].queue.red.maxths     = "4"  
**.router.eth[*].queue.red.maxps      = "1"
**.router.eth[*].queue.red.pkrates    = "833.3333"
**.router.eth[*].queue.red.frameQueueCapacity = 24

### CODE REVIEW

**Comment by screw** [comment]
Oh snap! Stupid me!
I thought the pull-request is back onto the original commit this branch diverged from and did not realise it is merging onto the latest commit in master.

Now I've tried to rebase it on top of the current master, but the changes are not as trivial as I hoped. The queue structure has changed a lot.
Is there any documentation that describes the hierarchy in which the various queue modules are stacked together?

Or even better (for me:)) - would it be trivial for you to update the code of (mainly) RedMarker which is heavily based on the previous version of RedDropper?

**Comment by ZoltanBojthe** [comment]
I will rebase your code to current master.
Please add one or more examples or tests for your pull-request.
This is needed to verify the rebased code.

**Comment by ZoltanBojthe** [comment]
rebased, refactored, but untested code available in https://github.com/inet-framework/inet/tree/topic/redmarker

**Comment by screw** [comment]
Thanks for the refactoring. We had a project meeting last week and I didn't get to it. I'll test it tomorrow.

**Comment by avarga** [comment]
To clarify, we rebased the topic branch in INET on top of master (that resolves the above conflicts), and currently waiting for your approval put it into master :)

**Comment by screw** [comment]
> To clarify, we rebased the topic branch in INET on top of master (that resolves the above conflicts), and currently waiting for your approval put it into master :)

I understand, I just didn't have the time to test it :).
I tried it today and I think it works correctly.

**Comment by ZoltanBojthe** [comment]
merged, closed

**Pull request closed without merging**
