### PR TITLE
Packetdrill for UDP, also for Windows

### PR DESCRIPTION
**Pull request by ruengeler**

### CODE REVIEW

**Comment by ruengeler** [comment]
@rhornig 
I made some changes and tested on Windows and Linux. I removed fmemopen.

**Comment by rhornig** [comment]
@ruengeler Thanks I will check this tomorrow.

**Comment by ruengeler** [comment]
Hi Rudolf,

did you forget checking the pull request?

Regards,

Irene
> Am 16.09.2015 um 17:05 schrieb Rudolf Hornig <notifications@github.com>:
> 
> @ruengeler <https://github.com/ruengeler> Thanks I will check this tomorrow.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/inet-framework/inet/pull/167#issuecomment-140769406>.
> 

*****************************************

Dr. Irene Rüngeler
Fachbereich Elektrotechnik und Informatik
Labor für Netzwerkprogrammierung, Datenbanklabor

Fachhochschule Münster
- University of Applied Sciences - 
Bismarckstr. 11, Raum 101
48565 Steinfurt

Tel: +49 2551 962-561 
Fax: +49 2551 962-563 
EMail: I.Ruengeler@fh-muenster.de

**Comment by rhornig** [comment]
@ruengeler I have created a new branch topic/packetdrill from this pull request and fixed a several issues. We made a review and we still have minor comments and issues. After fixing those, we are redi to merge the changes.

**Comment by ruengeler** [comment]
@rhornig 
I addressed Zoltan's comments from my previous pull request 
https://github.com/inet-framework/inet/commit/45bc23ba7ea36d16a5761156e21e4d1a8a203f7f
I did not change cTerminationException to cRuntimeError, because for me the outcome of the tests do not look as 'destructive' as with cRuntimeError. cTerminationException is used to indicate that a test failed. It is not a program error.

**Comment by rhornig** [comment]
Merged in 655a7986a7ed87fc741fd59444942e3df410c525

**Pull request closed without merging**
