### PR TITLE
Added implementation of the X-MAC linklayer protocol

### PR DESCRIPTION
**Pull request by ApolloLV**
This is the implementation of Joaquim Oller for the MiXiM framework that I ported to INET as a part of my bachelor thesis.
It is useful in the context of wireless sensor network simulations when considering low power listening protocols.

### CODE REVIEW

**Comment by levy** [comment]
Very nice! These are the kind of contributions we are looking for. We are going to look into this pull request and I hope merge soon. Do you think that you can help us out and also port it to INET 4.0 if requested? BTW, what does X stands for?

**Comment by ApolloLV** [comment]
X does not really stand for anything. It is just another protocol from the MAC alphabet soup.
(www.st.ewi.tudelft.nl/~koen/MACsoup/)

**Comment by levy** [comment]
Thank you anyway!

**Comment by levy** [comment]
We (my colleague Gyorgy Szaszko and me) are creating a showcase (a short tutorial) about wireless sensor network MAC protocols, namely B-MAC, L-MAC, and X-MAC. The documentation for the showcase is still a work in progress, you can find the current version here:

https://inet.omnetpp.org/inet-showcases/wireless/sensornetwork/

Could you please help us with some questions?

1. Can XMac work with an asymmetrical slotDuration (i.e. the slotDuration value is not the same for all nodes in the network)?

2. Currently, we use XMac with ApskScalarRadio, which always adds a PHY preamble and PHY header to the signal. We are unsure about how the MAC preamble is supposed to be represented at the PHY?

- PHY preamble + PHY header + some MAC data representing the MAC preamble (optionally zero bits?). This is what we have right now but this is probably wrong.
- PHY preamble (some predefined waveform), no PHY header, no MAC data and no PHY overhead at all? Is this the right interpretation?

**Comment by ApolloLV** [comment]
1. XMac could work, but my current implementation does not support asymmetry.
You could change [this line](https://github.com/inet-framework/inet/blob/4b415fead79e25a441dfda9cd5a6037d1bb82d9d/src/inet/linklayer/xmac/XMacLayer.cc#L324) so it schedules the message at the longest slot duration configured in the network instead of the slot duration of the current node.

**Pull request merged**
