### PR TITLE
Improving Rip routing protocol

### PR DESCRIPTION
**Pull request by ManiAm**
bug fixes
---------
- [in the old code] the RIP message was sent to the interface even when the interface is down!

- [in the old code] one of the 'for' loops was iterating over a vector while deleting some of the entries without considering the fact that the iterator gets invalidated after deletion. This led to segmentation fault in some cases.

improvements
------------
- separating the RIP route data from the main RIP code

- adding triggered update parameter to disable/enable triggered update (in the old code, triggered update was enabled all the time). The triggered update is enabled by default (as before), but one can disable it to see the slow convergence of the RIP protocol.

- adding the de-facto hold-down timer (it's not defined in the RFC, but it is present in many implementations such as Cisco routers). By default the timer is disabled, but it can be activated by setting a non-zero value.

- adding more comments throughout the code

- small code improvements and refactoring

### CODE REVIEW

**Comment by levy** [comment]
Thank you for the pull request!

This will take more time to review and merge, but I think this can go into integration before 4.0 is released.

**Comment by levy** [comment]
Indeed, this looks like the beginning of a very nice RIP tutorial, and it must be included in INET. Thanks!

**Comment by levy** [comment]
I merged your modifications into the integration branch unchanged except for splitting one of your patches. The patch in question changed the fingerprints of RIP examples (try: tests/fingprint$ ./fingerprinttest --debug -m rip) and I wanted to have the part which affects fingerprints as a separate patch to see what exactly is causing the change.

I also merged your tutorial into the integration branch under tutorials/rip. Gyuri, who is mostly working on showcases and tutorials, is going to create a skeleton markdown page for this one too. The skeleton page will explain the goals and the models, it will contain screenshots and videos, I guess. It would be very nice of you, if you could write a few sentences for each step. We will let you know if you can see the RIP tutorial section on the official web page.

Please check if everything is included as you expected.
Thank you very much!

**Comment by levy** [comment]
I wanted to let you know that we have added a documentation skeleton for the RIP tutorial you have sent us. The documentation can be found in the integration branch of the inet-tutorials repository, which is a git submodule of the INET repository. You can find the source in your INET project under the tutorials folder, but it is also available on github at:
https://github.com/inet-framework/inet-tutorials/tree/integration/rip

Unfortunately, there's very little real documentation yet on what's happening and why. We mostly created the tutorial pages, the main sections, and added some hints. There are also a few nice screenshots and some videos demonstrating the protocol in action. The tutorial is already available on the INET website if you want to check this out, but it is hidden from the public now:
https://inet.omnetpp.org/inet-tutorials/rip/doc/

If you would like to contribute some documentation to the individual steps, models or results, we would be very happy to include it! Nobody is working on this part at the moment, so it's safe to assume that your changes will be merged without conflicts.

Again, thank you for your contributions!

**Comment by levy** [comment]
Oh, I forgot to add the link to the markdown files:

https://github.com/inet-framework/inet-tutorials/tree/integration/_docs/rip

**Comment by ManiAm** [comment]
Ok, I will take a look at it on this weekend.

**Comment by ManiAm** [comment]
@levy I have started working on it, but need more time to finish it (due to my deadlines).

**Comment by levy** [comment]
@ManiAm ok, no problem. There's no need to hurry. Thank you for taking your time to contribute, we appreciate it!

**Pull request closed without merging**
