### PR TITLE
Work around omnetpp/omnetpp#867 by rounding down very small signal values

### PR DESCRIPTION
**Pull request by edlongman**
See  omnetpp/omnetpp#867 for long term fix to omnet but since the fix is not in omnet5 the work around is required

### CODE REVIEW

**Comment by levy** [comment]
Isn't this obsolete now that the related bug has been fixed in omnet?

**Comment by edlongman** [comment]
This will fix the inet version in omnet5.7 though, which will never receive the fix in omnet 6 I think.

**Comment by levy** [comment]
I guess you meant *will not*. I think it's not worth the hassle to fix the older INET version because this issue must very rarely affect anyone. Don't you think?

**Comment by edlongman** [comment]
I agree it's a rare issue.
Only really comes up in very large Sims and shouldn't be reported often
since omnet 6 will fix it

**Comment by levy** [comment]
Then I close this.

**Pull request closed without merging**
